In [ ]:
#Today's session is for  numpy


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.zeros((4,4))
b=np.ones((4,4))
print(a+b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
ac=np.arange(100,501,100)
print(ac)

[100 200 300 400 500]


In [ ]:
x=np.random.rand(3,3)
print(x.shape)
print(x.dtype)
print(x.ndim)

(3, 3)
float64
2


In [ ]:
import numpy as np
y=np.random.rand(12)
print(y)
z=y.reshape(3,4)
print(z)

[0.75669018 0.86177435 0.80477308 0.57561127 0.6356605  0.77027417
 0.81639856 0.8364437  0.84741982 0.93464253 0.84958155 0.93917669]
[[0.75669018 0.86177435 0.80477308 0.57561127]
 [0.6356605  0.77027417 0.81639856 0.8364437 ]
 [0.84741982 0.93464253 0.84958155 0.93917669]]


#PANDAS



In [ ]:
import pandas as pd
from google.colab import files
uploaded=files.upload()
df=pd.read_csv('sales_data.csv')

Saving sales_data.csv to sales_data (3).csv


In [ ]:
df.head()

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
1,102,Phone,20000,2,Mumbai
2,103,Tablet,30000,1,Delhi
3,104,Headphones,2000,3,Bangalore
4,105,Phone,20000,1,Mumbai


In [ ]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   order_id  8 non-null      int64 
 1   product   8 non-null      object
 2   price     8 non-null      int64 
 3   quantity  8 non-null      int64 
 4   city      8 non-null      object
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes


In [ ]:
df['order_id']

,order_id
0,101
1,102
2,103
3,104
4,105
5,106
6,107
7,108


In [ ]:
# df.loc[0]
df.iloc[0]
df.iloc[0:5]

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
1,102,Phone,20000,2,Mumbai
2,103,Tablet,30000,1,Delhi
3,104,Headphones,2000,3,Bangalore
4,105,Phone,20000,1,Mumbai


In [ ]:
# Filtering Conditions
df[(df['price']>25000)&(df['city']=='Delhi')]

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
2,103,Tablet,30000,1,Delhi
5,106,Laptop,50000,1,Delhi


In [ ]:
df[(df['price']>25000)|(df['city']=='Mumbai')]

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
1,102,Phone,20000,2,Mumbai
2,103,Tablet,30000,1,Delhi
4,105,Phone,20000,1,Mumbai
5,106,Laptop,50000,1,Delhi
6,107,Tablet,30000,2,Bangalore


In [ ]:
df.groupby('city')['price'].mean()

,price
city,
Bangalore,16000.0
Delhi,37500.0
Mumbai,20000.0


In [ ]:
df.groupby('city').agg({'price': 'mean', 'product':'count','quantity': 'max'})

,price,product,quantity
city,,,
Bangalore,16000.0,2,3
Delhi,37500.0,4,1
Mumbai,20000.0,2,2


In [ ]:
df.describe()
df.head()

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
1,102,Phone,20000,2,Mumbai
2,103,Tablet,30000,1,Delhi
3,104,Headphones,2000,3,Bangalore
4,105,Phone,20000,1,Mumbai


In [ ]:
df.isnull().sum()
df.dropna()

,order_id,product,price,quantity,city
0,101,Laptop,50000,1,Delhi
1,102,Phone,20000,2,Mumbai
2,103,Tablet,30000,1,Delhi
3,104,Headphones,2000,3,Bangalore
4,105,Phone,20000,1,Mumbai
5,106,Laptop,50000,1,Delhi
6,107,Tablet,30000,2,Bangalore
7,108,Phone,20000,1,Delhi


In [ ]:
df.merge(df['price'],df['order_id'] id=101 )